image:
  file: .gitpod.Dockerfile

# List the start up tasks. You can start them in parallel in multiple terminals. See https://www.gitpod.io/docs/44_config_start_tasks/
# tasks:
# # - init: echo 'init script' # runs during prebuild
# #   command: echo 'start script'
# - command: source qcbrunch-cli/envs/gitpod.sh
# - command: cd qcbrunch-cli && pipenv shell

tasks:
  # - command: make run
  # #TODO: pipenv install for qcbrunch-cli?
  - before: bash
    # init: npm install -g npm && npm install -g serve
    init: echo placeholder $SHELL
    # command: cd qcbrunch-cli && pipenv run qcbrunch dev run
    command: make run

ports:
  - port: 5001
    onOpen: open-preview
