image:
  file: .gitpod.Dockerfile

tasks:
  - init: >-
      cd "${GITPOD_REPO_ROOT}/qcbrunch-cli" &&
      pipenv install --skip-lock
    command: >-
      cd "${GITPOD_REPO_ROOT}/qcbrunch-cli" &&
      pipenv shell -- 'qcbrunch clean && qcbrunch render && qcbrunch build'
    openIn: bottom
    openMode: tab-after
  - command: >-
      cd "${GITPOD_REPO_ROOT}/qcbrunch-cli" &&
      sleep 3 &&
      pipenv shell -- 'qcbrunch dev serve'
      # wait 3s for build to complete
    openIn: bottom
    openMode: tab-after

ports:
  - port: 5001
    onOpen: open-preview
