image:
  file: .gitpod.Dockerfile

tasks:
  - init: >-
      cd "${GITPOD_REPO_ROOT}/qcbrunch-cli" &&
      pipenv install --skip-lock
    command: >-
      cd "${GITPOD_REPO_ROOT}/qcbrunch-cli" &&
      pipenv shell -- 'qcbrunch clean && qcbrunch render && qcbrunch build && gp sync-done virtual-env-setup'
    openIn: bottom
    openMode: tab-after
  - command: >-
      cd "${GITPOD_REPO_ROOT}/qcbrunch-cli" &&
      gp sync-await virtual-env-setup &&
      pipenv shell -- 'qcbrunch dev serve'
    openIn: bottom
    openMode: tab-after
  - command: gp open index.html && exit

ports:
  - port: 5001
    onOpen: open-preview
