name: Publish Image
description: Publish a Docker image to GitHub Package Registry
runs:
  using: docker
  image: Dockerfile
inputs:
  image:
    description: Docker image name + tag
    required: true
  username:
    description: GitHub username for GitHub Package Registry
    required: false
    default: tedmiston
  token:
    description: GitHub token for GitHub Package Registry
    required: true
