name: Healthchecks
inputs:
  status:
    description: Job status
    required: true
  url:
    description: Healthcheck URL
    required: true
  success-url:
    description: todo
    required: false
    default: ${{ inputs.url }}
  failure-url:
    description: todo
    required: false
    default: ${{ inputs.url }}/fail
runs:
  using: docker
  image: Dockerfile
  args:
    - ${{ inputs.status }}
    - ${{ inputs.url }}
