name: Healthchecks
inputs:
  status:
    description: Job status
    required: true
  url:
    description: Healthcheck URL
    required: true
runs:
  using: docker
  image: Dockerfile
  args:
    - ${{ inputs.status }}
    - ${{ inputs.url }}
