name: Healthchecks
inputs:
  status:
    description: Job status
    required: true
  url:
    description: Healthcheck URL
    required: true
  success-route:
    description: todo
    required: false
    default: ''
  failure-route:
    description: todo
    required: false
    default: /fail
runs:
  using: docker
  image: Dockerfile
  args:
    - ${{ inputs.status }}
    - ${{ inputs.url }}
