name: Healthchecks
inputs:
  status:
    description: Job status
    required: true
  url:
    description: Healthcheck URL
    required: true
  successRoute:
    description: todo
    required: false
    default: ''
  failureRoute:
    description: todo
    required: false
    default: /fail
runs:
  using: docker
  image: Dockerfile
