# FROM python:3.7.3-stretch
# FROM ubuntu:18.04
# FROM alpine
FROM node:alpine

# WORKDIR /github/workspace/

RUN env

RUN pwd
RUN ls -al
RUN uptime

# RUN cd qcbrunch-cli/ && pip install -e .

# ENV QCBRUNCH_ROOT /github/workspace

# RUN qcbrunch --help

# CMD qcbrunch --help
# CMD qcbrunch clean && qcbrunch render && qcbrunch build
