name: CI/CD
on: push
jobs:
  build:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - name: Git checkout
        uses: actions/checkout@master

      - name: Validate Dockerfiles
        uses: tedmiston/qcbrunch/docker/hadolint@master

      - name: Build site
        uses: docker://python:3.7-slim@sha256:589527a734f2a9e48b23cc4687848cb9503d0f8569fad68c3ad8b2ee9d1c50ff
        env:
          QCBRUNCH_ROOT: $GITHUB_WORKSPACE
        with:
          entrypoint: bash
          args: -c ./docker/qcbrunch-cli/app.sh

      - name: Validate HTML
        uses: tedmiston/qcbrunch/docker/html-validator@master

      - name: Validate CSS
        uses: docker://validator/validator:latest@sha256:33dd5741e96e2369398046fbdce3111d08e3b15e7fc12235655667eacc5d67d3
        with:
          args: /vnu-runtime-image/bin/vnu --skip-non-css --verbose build/css/

      - name: Validate JS
        uses: tedmiston/qcbrunch/docker/js-validator@master

      # TODO: troubleshoot random docker build failure
      # - name: Validate Markdown
      #   uses: igorshubovych/markdownlint-cli@c62b00d9a586560560b1151b38875deef047a093
      #   with:
      #     args: --ignore=_posts/ --ignore=node_modules/ .

      - name: Setup Node
        uses: actions/setup-node@master
        with:
          node-version: '12.x'

      - name: Install Now
        run: sudo npm install -g now

      - name: Deploy Dev
        if: github.ref != 'master'
        run: >
          cd build &&
          now deploy --prod --token=${{ secrets.ZEIT_TOKEN }} --no-clipboard --local-config=now.dev.json

      - name: Deploy Prod
        if: github.ref == 'master'
        run: >
          cd build &&
          now deploy --prod --token=${{ secrets.ZEIT_TOKEN }} --no-clipboard --local-config=now.json
