name: Docker
on:
  push:
    paths:
      - .github/workflows/docker.yml
      - docker/**
      - Makefile
env:
  DOCKER_BUILDKIT: 1
  REGISTRY_TOKEN: ${{ secrets.GITHUB_PACKAGE_REGISTRY_TOKEN }}
jobs:
  build-hadolint:
    name: Build Hadolint
    runs-on: ubuntu-latest
    steps:
      - name: Git checkout
        uses: actions/checkout@v1
      - name: Build image
        run: >
          cd docker/hadolint &&
          docker build -t docker.pkg.github.com/tedmiston/qcbrunch/hadolint:${{ github.sha }} .
      - name: Publish image
        run: make publish-image
        env:
          IMAGE: hadolint:${{ github.sha }}
  build-html-validator:
    name: Build HTML validator
    runs-on: ubuntu-latest
    steps:
      - name: Git checkout
        uses: actions/checkout@v1
      - name: Build image
        run: >
          cd docker/html-validator &&
          docker build -t docker.pkg.github.com/tedmiston/qcbrunch/html-validator:${{ github.sha }} .
      - name: Publish image
        run: make publish-image
        env:
          IMAGE: html-validator:${{ github.sha }}
  build-js-validator:
    name: Build JS validator
    runs-on: ubuntu-latest
    steps:
      - name: Git checkout
        uses: actions/checkout@v1
      - name: Build image
        run: >
          cd docker/js-validator &&
          docker build -t docker.pkg.github.com/tedmiston/qcbrunch/js-validator:${{ github.sha }} .
      - name: Publish image
        run: make publish-image
        env:
          IMAGE: js-validator:${{ github.sha }}
