name: Docker
on:
  push:
    paths:
      - .github/workflows/docker.yml
      - 'docker/**'
jobs:
  build-hadolint:
    name: Build Hadolint
    runs-on: ubuntu-latest
    steps:
      - name: Git checkout
        uses: actions/checkout@v1
      - name: Build image
        run: >
          cd docker/hadolint &&
          docker build -t docker.pkg.github.com/tedmiston/qcbrunch/hadolint:${{ github.sha }} .
      - name: Publish image
        run: >
          echo ${{ secrets.GITHUB_PACKAGE_REGISTRY_TOKEN }} | docker login --username=tedmiston --password-stdin docker.pkg.github.com &&
          docker push docker.pkg.github.com/tedmiston/qcbrunch/hadolint:${{ github.sha }} &&
          docker logout docker.pkg.github.com
  build-html-validator:
    name: Build HTML validator
    runs-on: ubuntu-latest
    steps:
      - name: Git checkout
        uses: actions/checkout@v1
      - name: Build image
        run: >
          cd docker/html-validator &&
          docker build -t tedmiston/qcbrunch:${{ github.sha }}-html-validator .
  build-js-validator:
    name: Build JS validator
    runs-on: ubuntu-latest
    steps:
      - name: Git checkout
        uses: actions/checkout@v1
      - name: Build image
        run: >
          cd docker/js-validator &&
          docker build -t tedmiston/qcbrunch:${{ github.sha }}-js-validator .
