name: Keep Alive
on:
  schedule:
    - cron: "30 0 * * *"

jobs:
  keep-alive:
    name: Keep Alive
    runs-on: ubuntu-latest
    steps:
      - name: Keep Alive
        uses: gautamkrishnar/keepalive-workflow@master
        with:
          time_elapsed: 1
