# GitHub suspends cron-based workflows for "inactivity" when there hasn't been
# new commits in the repo in 60 days.  This results in breaking workflows on
# static sites which don't need to be updated very regularly.
# 
# This workflow puts a bandaid on that nuisance by generating a dummy commit,
# when needed, to avoid the repo getting flagged for "inactivity".

name: Keep Alive

on:
  schedule:
    - cron: 0 0 * * *

jobs:

  keep-alive:
    name: Keep Alive
    runs-on: ubuntu-latest
    steps:

      - name: Git checkout
        uses: actions/checkout@v2

      - name: Keep Alive
        uses: gautamkrishnar/keepalive-workflow@master
        with:
          committer_username: Robot
          committer_email: robot@taylore.dev
          commit_message: Keep alive
          time_elapsed: 30
